image: node:latest
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  environment:
    name: staging
  artifacts:
    paths:
      - public